title: oumae docs
description: Официальная документация oumae
theme: just-the-docs

url: https://oumae-mk.github.io/docs

nav_external_links:
  - title: "Oumae в Telegram"
    url: https://t.me/+bHgaMW-ajFhkY2Fi

callouts:
  note:
    title: ""
    color: grey-lt
  warning:
    title: ""
    color: grey-dk

color_scheme: oumae_light

back_to_top: true
back_to_top_text: "Наверх ↑"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Редактировать эту страницу на GitHub."
gh_edit_repository: "https://github.com/oumae-mk/docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"
