title: oumae docs
description: Официальная документация oumae
theme: just-the-docs

url: https://oumae-mk.github.io/docs

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
