title: oumae docs
description: Официальная документация oumae
theme: just-the-docs

url: https://oumae-mk.github.io/docs

nav_external_links:
  - title: "Oumae в Telegram"
    url: https://t.me/+bHgaMW-ajFhkY2Fi

callouts:
  note:
    title: ""
    color: grey-lt
  warning:
    title: ""
    color: grey-dk

color_scheme: oumae_light
